import { Inter } from "next/font/google";
import StyledComponentsRegistry from "../libs/AntdRegistry";
import LayoutCustom from "./default-layout";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <LayoutCustom>{children}</LayoutCustom>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
